AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates and associates NLB with a newly created VPC Link.

#Metadata:

#Parameters:

Resources: 
  SampleAppVPCLink:
    Type: AWS::ApiGateway::VpcLink
    DependsOn: SampleAppNLB
    Properties:
      Description: Creates a VPC Link 
      Name: SampleAppVPCLink
      TargetArns: 
        - !Ref SampleAppNLB
      
  SampleAppNLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: SampleApp-NLB
      Type: network
      Scheme: internal
      Subnets: 
      - !ImportValue SampleAppVPC-PublicSubnet1
      - !ImportValue SampleAppVPC-PublicSubnet2

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Name: NLB-VPC-LINK-TG
      Port: 80
      Protocol: TCP
      VpcId: !ImportValue SampleAppVPC-VPC

  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup
      LoadBalancerArn: !Ref SampleAppNLB
 
Outputs:
  SampleAppVPCLink:
    Description: VPC Link for Sample App APIs
    Value: !Ref SampleAppVPCLink
    Export:
      Name: SampleAppVPCLink
  
  SampleAppNLB:
    Description: NLB for VPC Link
    Value: !Ref SampleAppNLB
    Export:
      Name: SampleAppNLB
      